export const MAIN_SCREEN = 'MAIN_SCREEN';
export const CREATING_CHARACTER = 'CREATING_CHARACTER';
export const VIEWING_CHARACTER = 'VIEWING_CHARACTER';
export const EDITING_CHARACTER = 'EDITING_CHARACTER';
